### ISSUE TITLE
Issue loading HLA model

### ISSUE THREAD

**Issue by shashidhar22** [Sun-lab/DePTH#1] opened 2024-04-15 19:32 UTC
I am trying to run DepTH on example data. I have setup DePTH in a conda environment as recommended in the tutorials. However, when I run the predict workflow I get the following model load error
```
ValueError: File format not supported: filepath=~/miniforge3/envs/depth/lib/python3.9/site-packages/DePTH/data/trained_models/HLA_I_all_match/HLA_I_all_match_model_5779_7821_6367. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(~/miniforge3/envs/depth/lib/python3.9/site-packages/DePTH/data/trained_models/HLA_I_all_match/HLA_I_all_match_model_5779_7821_6367, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).
```

The recommended solution in the error message doesn't work either. When I try loading the model using `TFSMLayer` I get the following error
```
AttributeError: 'TFSMLayer' object has no attribute 'predict'
```

**Comment by liusi2019** [comment] 2024-05-18 07:14
Sorry that I didn't see this issue until now. This is an issue caused by that the lastest TensorFlow version will come with Keras 3, which leads to incompatibility of the model loading step. This issue is now fixed by restricting the TensorFlow version. The updated version of the package has been uploaded to PyPI. On my end, setting up a new conda environment following the procedure as in the tutorial works now. Feel free to let me know if there are still issues.

**Closed as completed** 2024-05-18 07:16 UTC
